In [1]:
import wandb

c:\Users\Csaba\anaconda3\envs\myenv\Lib\site-packages\pydantic\_internal\_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
c:\Users\Csaba\anaconda3\envs\myenv\Lib\site-packages\pydantic\_internal\_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(

In [2]:
wandb.login()

wandb: Currently logged in as: csczuth (csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [3]:
import pandas as pd
import wandb
import json

api = wandb.Api()
entity, project = "csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem", "federated-learning"
runs = api.runs(entity + "/" + project)

summary_list, config_list, accuracies, name_list, sys_usage_dfs, strategy, clients, rounds = [], [], [], [], [], [], [], []
for run in runs:
    # .summary contains the output keys/values
    #  for metrics such as accuracy.
    #  We call ._json_dict to omit large files
    summary_list.append(run.summary._json_dict)
    print(run)
    config_list.append({})
    tmp_df = run.history(stream="events")
    tmp_df["run_id"] = run.id
    sys_usage_dfs.append(tmp_df)
    # .config contains the hyperparameters.
    #  We remove special values that start with _.
    s = json.loads(run.config)
    rounds_tmp, strategy_tmp, clients_num_tmp = s.get("number_of_rounds", {}).get("value"), s.get("strategy", {}).get("value"), s.get("min_clients", {}).get("value")
    rounds.append(rounds_tmp)
    strategy.append(strategy_tmp)
    clients.append(clients_num_tmp)
    try:
        #config_list.append({k: v for k, v in run.config.items() if not k.startswith("_")})
        tmp_acc = []
        # if run.state == "finished":
        for i, row in run.history().iterrows():
            tmp_acc.append(row["accuracy"])
        accuracies.append(tmp_acc)
    except Exception as e:
        #config_list.append({})
        print('erroor in accuracy extraction for run ', run.id)
        accuracies.append([])

    # .name is the human-readable name of the run.
    name_list.append(run.id)
    

runs_df = pd.DataFrame(
    {#"summary": summary_list, "config": config_list, 
     "accuracies": accuracies, "name": name_list, "rounds": rounds, "strategy": strategy, "clients_num": clients}
)

runs_df.to_csv("project.csv")
# for s in sys_usage_dfs:
#     print(s)

<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/mtblu6fm (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/2rs2p3o8 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/jrtv3cqw (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/583zq665 (finished)>
erroor in accuracy extraction for run  583zq665
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/hi88bhix (finished)>
erroor in accuracy extraction for run  hi88bhix
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/2pf362ki (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/v4uf1jk4 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/laapbv3g (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/axkiqeth (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/huwxmkh3 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/q1ws053x (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/guro9jz1 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/f2ocjxuy (failed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/xxhgzgv8 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/rrbki6vm (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/1m80m882 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/1brq6jfr (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/38fkwz6p (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/o32fd7rs (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/p0pwgj8w (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/zqiehm95 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/w70dzdmp (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/57w8ouka (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/958yoqsi (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/7fxvbfee (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/yk36g5j3 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/b764ct16 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/mzya6840 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/6pepwy5c (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/n583e8ro (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/lifdpu1a (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/xfgjo2kh (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/5zz1ywkt (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/fbt936q2 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/wpzcrjss (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/0clfpsmh (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/9algp5th (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/hsghawpc (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/pgs89kvc (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ua8mqd1x (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ruf9p9mc (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ttbfmwya (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/41k4dhck (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/23eda9d7 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/m7loe8je (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/2fuba1sy (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/zsdihtxn (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/gdfp2fgo (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/6hzt7jmo (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ahk8ncpo (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/tb27n0wg (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/z6tnidj4 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/r0sjacnu (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/71pomgcu (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/rcf9zyfr (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/0kap07g1 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/yfr7xvsb (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/cm2ekp8t (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/4u8zdahu (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/69jt0x1u (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ne5n7o1a (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/vm7x3yef (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/iy3zxoib (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/k02wgfx2 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/1bw0qtgy (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/h10yropn (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/80q3isi3 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/b7w3p1ab (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/07j9ue8u (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/3wmgbw66 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/skmck0bz (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/shpn2hym (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/nsy1ns1i (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/vqu4u911 (failed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ay2z5mfo (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/mkyw48to (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/7akr2gv8 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/qchofjvr (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/60vzdohx (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/3702wvrt (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ud2v5b6c (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ys28bwex (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/atp7bxid (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/bc6bxgcy (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/xukmccrm (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/opjp7mz3 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/jy172gnb (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/4cim1l0e (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/cx3dqpke (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/egxiqyik (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/nls5otqb (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/xbeatox4 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/0k5yb82p (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/7xkhcjmi (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/pt7jmpta (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/xebi937k (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ciuew3g9 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/03ztzqmd (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/tsejea7r (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/8owzmgmx (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ooq7pk9m (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/yuoudlv2 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/nokllshp (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/uecqrdy8 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/yjnpdbz5 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/iz2exogo (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/sr8uqdy5 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/26frbfjt (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/4ptwaqfr (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/8wlk6o1z (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/5i1qw531 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/r98pefaj (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/0innfz83 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/oc5d0vlz (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/w61r501i (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/gyrptumg (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/au3u9qg2 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/3c6mdl2x (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/03nug88h (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/aw5svks0 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/tummm3fu (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/e2ahz17j (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ue14lsfw (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/udu6bqce (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/xga8x0n0 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/8t9zj79e (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/7inf7ye9 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/v6mgfdtz (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/bb00bz2h (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/bapv36vf (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/okcb4qxd (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/kcxmzsev (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ufnn5pwz (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/k30spfko (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/wkqjg8d2 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/dtwd9hux (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/a6fuhpmg (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/8gerv1dy (failed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/592yyio6 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/0pv3cfgu (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/qov3nixr (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/jedg5d5y (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ycokv3fy (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/relwpm4d (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/5927lhg8 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/byrx6mre (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/13j28u2o (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/m6zdl2aa (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/5jkkqdb0 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/g1dflqw7 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/4t6go771 (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/xv5yvc3r (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/yrefj9dh (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/1k1o1jgk (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/i2mmuvcw (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/h4wjvfrh (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/p2jppkg1 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/hebgylq7 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/nb1t0l88 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/mu7mjmeh (failed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/8z0yadky (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/fo2z8qg0 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/pxmjb3lk (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/qc5tm1lt (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/3fa13f9h (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/i0a4jqp5 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/5wihds7z (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/9widh9iq (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ptde2lgi (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/grn8n6rc (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/esvawn2m (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/0qbonjgc (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/lxqab2yj (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/j4d6a3zv (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/ur0e5uid (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/q2bal1sf (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/l6r1u49a (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/buxistx7 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/rzc80e59 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/n9ma20gq (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/61dhq8c9 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/2fzjd5px (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/spyop9o8 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/5rqmvf0x (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/2gvms1df (crashed)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/lwp0h7xx (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/hnb1ej80 (finished)>
<Run csczuth-budapesti-m-szaki-s-gazdas-gtudom-nyi-egyetem/federated-learning/1056hycy (finished)>

In [4]:
runs_df['max_accuracy'] = runs_df.apply(lambda row: max(row["accuracies"]) if len(row["accuracies"]) > 0 else 0, axis=1)

In [5]:
fedavgs = runs_df[(runs_df['strategy'] == 'FedAvg') & (runs_df['rounds'] <= 100) & (runs_df['max_accuracy'] < 0.66)]
#fedavgs
fedavgs.groupby('clients_num')['max_accuracy'].max().reset_index().to_csv("scalability.csv", index=False)

In [6]:
fedadams = runs_df[(runs_df['strategy'] == 'FedAdam') | (runs_df['strategy'] == 'FedAdamDefault')]

In [7]:
fedadams

,accuracies,name,rounds,strategy,clients_num,max_accuracy
45,"[0.28413793103448276, 0.38068965517241377, 0.3...",2fuba1sy,10.0,FedAdamDefault,2.0,0.431724
137,[],8gerv1dy,100.0,FedAdam,2.0,0.000000
138,"[0.30896551724137933, 0.3020689655172414, 0.26...",592yyio6,100.0,FedAdam,2.0,0.308966
139,"[0.19724137931034483, 0.3255172413793103, 0.30...",0pv3cfgu,100.0,FedAdam,2.0,0.337931
158,"[0.31336405529953915, 0.29493087557603687, 0.2...",nb1t0l88,10.0,FedAdamDefault,32.0,0.373272
159,[0.2798165137614679],mu7mjmeh,10.0,FedAdamDefault,32.0,0.279817
160,"[0.2672811059907834, 0.2626728110599078, 0.299...",8z0yadky,10.0,FedAdamDefault,32.0,0.377880
161,"[0.2488479262672811, 0.30414746543778803, 0.27...",fo2z8qg0,10.0,FedAdamDefault,32.0,0.341014
162,"[0.2857142857142857, 0.25806451612903225, 0.23...",pxmjb3lk,400.0,FedAdamDefault,32.0,0.428571
165,"[0.26146788990825687, 0.2857142857142857, 0.26...",i0a4jqp5,100.0,FedAdamDefault,32.0,0.506912
166,"[0.24770642201834864, 0.2488479262672811, 0.28...",5wihds7z,150.0,FedAdam,32.0,0.479263
167,"[0.271889400921659, 0.2903225806451613, 0.2764...",9widh9iq,150.0,FedAdam,32.0,0.486239
168,"[0.34101382488479265, 0.25229357798165136, 0.2...",ptde2lgi,150.0,FedAdam,32.0,0.470046
169,"[0.27522935779816515, 0.2672811059907834, 0.32...",grn8n6rc,150.0,FedAdam,32.0,0.377880
170,"[0.16972477064220184, 0.16589861751152074, 0.1...",esvawn2m,150.0,FedAdam,32.0,0.364055
171,"[0.2119815668202765, 0.2764976958525346, 0.281...",0qbonjgc,150.0,FedAdam,32.0,0.460829
172,"[0.20276497695852536, 0.1889400921658986, 0.14...",lxqab2yj,150.0,FedAdam,32.0,0.470046
173,"[0.19815668202764977, 0.1926605504587156, 0.16...",j4d6a3zv,150.0,FedAdam,32.0,0.442396
174,"[0.21658986175115208, 0.22119815668202766, 0.2...",ur0e5uid,150.0,FedAdam,32.0,0.400922
175,"[0.22018348623853212, 0.17972350230414746, 0.1...",q2bal1sf,150.0,FedAdam,32.0,0.437788
176,"[0.3211009174311927, 0.2672811059907834, 0.248...",l6r1u49a,400.0,FedAdam,32.0,0.493088

In [19]:
strats = runs_df[(runs_df['rounds'] >= 100) & (runs_df['clients_num'] > 4)]
strats = strats[~strats['strategy'].str.contains('Default')]

In [21]:
strats.groupby("strategy").agg(max_accuracy=("max_accuracy", "max"),client_nums=("clients_num", "first")).reset_index()
#.to_csv("strategy_comparison.csv", index=False)
#.to_csv("scalability.csv", index=False)

        strategy  max_accuracy  client_nums
0     FedAdagrad      0.506912         32.0
1        FedAdam      0.493088         32.0
2         FedAvg      0.824885         32.0
3        FedAvgM      0.697248         32.0
4          FedCM      0.555046         32.0
5        FedProx      0.788018         32.0
6  FedTrimmedAvg      0.587156         32.0
7        FedYogi      0.511521         32.0